<a href="https://colab.research.google.com/github/munjihun-git/classroom/blob/main/03_data_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 3. 데이터 전처리

## 3.1 결측치 처리하기

In [2]:
# Seaborn 라이브러리 임포트
import seaborn as sns

# Pandas 라이브러리를 사용하여 CSV 파일 불러오기
titanic_data = sns.load_dataset('titanic')
titanic_data.head()  # 데이터의 처음 5행 출력

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [3]:
# 결측치 확인
missing_values = titanic_data.isnull().sum()
missing_values

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [4]:
# 'age' 컬럼의 결측치를 중앙값으로 대체
titanic_data['age'].fillna(titanic_data['age'].median(), inplace=True)

# 결측치 재확인
titanic_data.isnull().sum()

survived         0
pclass           0
sex              0
age              0
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

## 3.2 데이터 타입 변환하기

In [5]:
# 'sex' 컬럼의 데이터 타입을 문자열에서 숫자로 변환 (male: 0, female: 1)
titanic_data['sex'] = titanic_data['sex'].map({'male': 0, 'female': 1})
titanic_data.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,0,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,1,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,1,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,1,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,0,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

## 3.3 필요한 열만 선택하기

In [6]:
# 'survived', 'pclass', 'sex', 'age' 열만 선택
selected_data = titanic_data[['survived', 'pclass', 'sex', 'age']]
selected_data.head()

   survived  pclass  sex   age
0         0       3    0  22.0
1         1       1    1  38.0
2         1       3    1  26.0
3         1       1    1  35.0
4         0       3    0  35.0